@host = http://127.0.0.1:5000


### Create a new item
POST {{host}}/orders
Content-Type: application/json

{
    "customerId": 15,
    "orderDate": "04/12/2023",
    "orderTime": "11:35",
    "productId": 2,
    "quantity": 5
}


### Read the list
GET {{host}}/orders
Content-Type: application/json


### Read a single item by id
###Read a single OrderId with multiple products
GET {{host}}/orders/54
Content-Type: application/json


### Update an item
PUT {{host}}/orders/54
Content-Type: application/json

{
    "productId": 2,
    "quantity": 1
}
### Update an item's status
PUT {{host}}/orders/status/54
Content-Type: application/json

{
    "status": "Served"
}



### Delete an item
DELETE {{host}}/orders/59
Content-Type: application/json


#PRODUCTS


### Create a new item
POST {{host}}/cafe/customer
Content-Type: application/json

{
    
    "fName": "Test",
    "lName": "Test Juan",
    "tblNum": "4"
  }


### Read the list
GET {{host}}/cafe/menu
Content-Type: application/json


### Read a single item by id
GET {{host}}/cafe/customer/15
Content-Type: application/json


### Update an item
PUT {{host}}/cafe/customer/15
Content-Type: application/json

{
    
    "fName": "Irish",
    "lName": "San Juan",
    "tblNum": "4"
  }
  


### Delete an item
DELETE {{host}}/cafe/customer/15
Content-Type: application/json




#PAYMENT


### Create a new item
POST {{host}}/payment
Content-Type: application/json

{
  "orderId": 13
}
### Update 

PUT {{host}}/payment/33
Content-Type: application/json

{
  "status": "Paid"
}

### Read the list
GET {{host}}/payment
Content-Type: application/json


### Read a single item by id
GET {{host}}/payment/59
Content-Type: application/json